sudo: required
language: generic
services:
    -docker

before_install:
  - docker build -t kkularatne/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kkularatne/docker-react npm run test
